// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7KABcP7kFS_UOvnckhi5l9ee5ItxBPwM',
    appId: '1:494723238803:web:d7e46047d2e7e355b1f666',
    messagingSenderId: '494723238803',
    projectId: 'maruti-kirba',
    authDomain: 'maruti-kirba.firebaseapp.com',
    storageBucket: 'maruti-kirba.firebasestorage.app',
    measurementId: 'G-BTJERC5NLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufyeGDJJHirrwgJbLXtlOViidQBDMr9k',
    appId: '1:494723238803:android:39559df9c7a3103db1f666',
    messagingSenderId: '494723238803',
    projectId: 'maruti-kirba',
    storageBucket: 'maruti-kirba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHjmUMDjCHrRQCqwLdwVXeDcNgUVxOe2M',
    appId: '1:494723238803:ios:f0ebba2bc7730d10b1f666',
    messagingSenderId: '494723238803',
    projectId: 'maruti-kirba',
    storageBucket: 'maruti-kirba.firebasestorage.app',
    iosBundleId: 'com.example.marutiKirbaLightingSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHjmUMDjCHrRQCqwLdwVXeDcNgUVxOe2M',
    appId: '1:494723238803:ios:f0ebba2bc7730d10b1f666',
    messagingSenderId: '494723238803',
    projectId: 'maruti-kirba',
    storageBucket: 'maruti-kirba.firebasestorage.app',
    iosBundleId: 'com.example.marutiKirbaLightingSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7KABcP7kFS_UOvnckhi5l9ee5ItxBPwM',
    appId: '1:494723238803:web:3a8ec7f7cb844ebdb1f666',
    messagingSenderId: '494723238803',
    projectId: 'maruti-kirba',
    authDomain: 'maruti-kirba.firebaseapp.com',
    storageBucket: 'maruti-kirba.firebasestorage.app',
    measurementId: 'G-6CLWJJMN39',
  );
}
